# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather group facts
      ansible.builtin.getent:
        database: group
    - name: Set assert variables
      ansible.builtin.set_fact:
        registered_groups: "{{ ansible_facts.getent_group }}"
    ## パッケージのテスト
    - name: Assert docker package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['docker-ce'] is defined
          - ansible_facts.packages['docker-ce-cli'] is defined
          - ansible_facts.packages['containerd.io'] is defined
          - ansible_facts.packages['docker-buildx-plugin'] is defined
          - ansible_facts.packages['docker-compose-plugin'] is defined
    ## グループのテスト
    - name: Assert docker group
      ansible.builtin.assert:
        that:
          - registered_groups['docker'] is defined
    ## 設定ファイルのテスト
    - name: Check docker setting
      ansible.builtin.stat:
        path: /etc/docker/daemon.json
      register: docker_setting_result
    - name: Assert docker setting
      ansible.builtin.assert:
        that:
          - docker_setting_result.stat.exists
    ## ufw-dockerのテスト
    - name: Test ufw-docker
      block:
        - name: Check installed ufw-docker
          ansible.builtin.stat:
            path: /usr/local/bin/ufw-docker
          register: ufw_docker_result
        - name: Assert ufw-docker
          ansible.builtin.assert:
            that:
              - ufw_docker_result.stat.exists
              - ufw_docker_result.stat.executable
        - name: Check ufw-docker apply setting(1)
          ansible.builtin.lineinfile:
            path: /etc/ufw/after.rules
            line: "# BEGIN UFW AND DOCKER"
          register: begin_ufw_docker_setting_line
          check_mode: true
        - name: Check ufw-docker apply setting(w)
          ansible.builtin.lineinfile:
            path: /etc/ufw/after.rules
            line: "# END UFW AND DOCKER"
          register: end_ufw_docker_setting_line
          check_mode: true
        - name: Assert applied ufw-docker
          ansible.builtin.assert:
            that:
              - begin_ufw_docker_setting_line is not changed
              - end_ufw_docker_setting_line is not changed
    ## サービスのテスト
    - name: Assert docker service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'] is defined
          - ansible_facts.services['docker.service']['state'] == 'running'
          - ansible_facts.services['docker.service']['status'] == 'enabled'
    - name: Assert containerd service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['containerd.service'] is defined
          - ansible_facts.services['containerd.service']['state'] == 'running'
          - ansible_facts.services['containerd.service']['status'] == 'enabled'
