# code: language=ansible
---
- name: Install repository dependency packages
  ansible.builtin.apt:
    name:
      - python3-apt
      - python3-debian
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
## @see https://docs.docker.com/engine/install/debian/#install-using-the-repository
- name: Create GPG key directory
  ansible.builtin.file:
    path: "{{ docker_apt_key_dest | dirname }}"
    state: directory
    mode: "0755"
- name: Download GPG key
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: "{{ docker_apt_key_dest }}"
    mode: "0644"
- name: Add docker repository
  ansible.builtin.deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts.distribution_release }}"
    components: stable
    signed_by: "{{ docker_apt_key_dest }}"
    enabled: true
    state: present
  register: apt_repository_result
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: apt_repository_result is changed
