# code: language=ansible
---
## @see https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot-with-systemd
- name: Service docker is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
- name: Service containerd is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true
